# Generated by Django 5.0.4 on 2024-05-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("gender", models.CharField()),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("sumofrating", models.IntegerField(default=0)),
                ("ppl", models.IntegerField(default=0)),
                ("age", models.IntegerField()),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassengerTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username1", models.CharField()),
                ("username2", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="PublisherTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, null=True)),
                ("phoneNumber", models.CharField(max_length=20, null=True)),
                ("source", models.CharField(max_length=100, null=True)),
                ("destination", models.CharField(max_length=100, null=True)),
                ("date", models.CharField(max_length=20, null=True)),
                ("time", models.CharField(max_length=20, null=True)),
                ("wheele", models.IntegerField(null=True)),
                ("vehicle", models.CharField(null=True)),
                ("seats", models.CharField(blank=True, default=1, null=True)),
                (
                    "discription",
                    models.CharField(blank=True, default="NONE", null=True),
                ),
                ("req1", models.CharField(blank=True, default="NONE", null=True)),
                ("req2", models.CharField(blank=True, default="NONE", null=True)),
                ("req3", models.CharField(blank=True, default="NONE", null=True)),
                (
                    "requested_by",
                    models.CharField(blank=True, default="NONE", null=True),
                ),
            ],
        ),
    ]
