# Generated by Django 5.0.4 on 2024-05-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clienttable",
            name="email",
            field=models.CharField(blank=True, default="none", null=True),
        ),
    ]
