# Generated by Django 5.0.4 on 2024-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_clienttable_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishertable",
            name="date",
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="publishertable",
            name="time",
            field=models.TimeField(max_length=20, null=True),
        ),
    ]
