# Generated by Django 5.0.4 on 2024-05-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_publishertable_date_alter_publishertable_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassengerDTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username1", models.CharField(max_length=150, unique=True)),
                ("username2", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PublisherDTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username1", models.CharField(max_length=150, unique=True)),
                ("username2", models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
