# Generated by Django 5.0.4 on 2024-05-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_passengerdtable_publisherdtable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passengerdtable",
            name="username1",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="passengerdtable",
            name="username2",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="publisherdtable",
            name="username1",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="publisherdtable",
            name="username2",
            field=models.CharField(max_length=150),
        ),
    ]
