# Generated by Django 5.0.4 on 2024-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_passengerdtable_username1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishertable",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
