# Generated by Django 5.0.4 on 2024-06-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_passengertable_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="passengertable",
            name="date",
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="passengertable",
            name="destination",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="passengertable",
            name="source",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="passengertable",
            name="time",
            field=models.TimeField(max_length=20, null=True),
        ),
    ]
