# Generated by Django 5.0.4 on 2024-08-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0008_passengertable_date_passengertable_destination_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="publishertable",
            name="complet",
            field=models.CharField(blank=True, default="NONE", null=True),
        ),
    ]
