# Generated by Django 5.0.4 on 2024-08-25 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_publishertable_complet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishertable",
            name="finished",
        ),
    ]
