# Generated by Django 5.0.4 on 2024-08-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_remove_publishertable_finished"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishertable",
            name="complet",
        ),
        migrations.AddField(
            model_name="publishertable",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
